# Generated by Django 4.1.3 on 2022-11-01 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameProduct', models.CharField(max_length=255)),
                ('Amount', models.IntegerField(max_length=10)),
                ('WholesalePrice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('RetailPrice', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateOfSale', models.DateField()),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UchetTovarov.availability')),
            ],
        ),
    ]
