# Generated by Django 4.1.3 on 2022-11-01 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UchetTovarov', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='Amount',
            field=models.IntegerField(),
        ),
    ]
